tela consulta_notas abre
Matheusouza2/academic_hub pull request #94
Opened 2024-06-12 00:05 UTC by emanuelflavio

2024-06-12 13:37 UTC, Matheusouza2 requested changes

2024-06-12 13:37 UTC, Matheusouza2 commented on frontend/src/components/Sidebar.tsx
> +        {OPTIONS[0].map((option) => (
Isso implica que o usuário sempre receberá a mesma sidebar, o ideal é ela ser dinamica com base no usuário logado

2024-06-13 14:38 UTC, emanuelflavio commented on frontend/src/components/Sidebar.tsx
> +        {OPTIONS[0].map((option) => (
Estava dando erro no sidebar, e pra aparecer só fazendo isso, mas essa task pelo oq eu vi é de garcez, e eu falei com ele e e ele disse que ja concertou, então de resto vai dar certo

2024-06-13 18:10 UTC, emanuelflavio commented
Já modifiquei para a mudança que garcez fez

2024-06-14 12:46 UTC, Matheusouza2 approved these changes

2024-06-14 12:46 UTC, merged