Correção List disciplina
Matheusouza2/academic_hub pull request #95
Opened 2024-06-12 00:10 UTC by jhonks83

Agora a Listagem de disciplinas esta abrindo e melhorei com o useEffect

2024-06-13 14:50 UTC, Matheusouza2 requested changes

2024-06-13 14:50 UTC, Matheusouza2 commented on frontend/src/components/Sidebar.tsx
> +        {OPTIONS[0].map((option) => (
Dessa forma o sidebar deixa de ser dinamico de acordo com o usuário logado

2024-06-14 13:47 UTC, jhonks83 commented on frontend/src/components/Sidebar.tsx
> +        {OPTIONS[0].map((option) => (
mandei sem querer o sidebar junto com a pr, vou alterar e terminar a que eu falto professor

2024-06-14 23:41 UTC, Matheusouza2 approved these changes

2024-06-14 23:41 UTC, merged